// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/edgexfoundry/edgex-go/core/domain/models"

// AddressableClient is an autogenerated mock type for the AddressableClient type
type MockAddressableClient struct {
	mock.Mock
}

// Add provides a mock function with given fields: addr
func (_m *MockAddressableClient) Add(addr *models.Addressable) (string, error) {
	ret := _m.Called(addr)

	var r0 string
	if rf, ok := ret.Get(0).(func(*models.Addressable) string); ok {
		r0 = rf(addr)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.Addressable) error); ok {
		r1 = rf(addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddressableForName provides a mock function with given fields: name
func (_m *MockAddressableClient) AddressableForName(name string) (models.Addressable, error) {
	ret := _m.Called(name)

	var r0 models.Addressable
	if rf, ok := ret.Get(0).(func(string) models.Addressable); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(models.Addressable)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
