// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/edgexfoundry/edgex-go/core/domain/models"

// DeviceProfileClient is an autogenerated mock type for the DeviceProfileClient type
type MockDeviceProfileClient struct {
	mock.Mock
}

// Add provides a mock function with given fields: dp
func (_m *MockDeviceProfileClient) Add(dp *models.DeviceProfile) (string, error) {
	ret := _m.Called(dp)

	var r0 string
	if rf, ok := ret.Get(0).(func(*models.DeviceProfile) string); ok {
		r0 = rf(dp)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.DeviceProfile) error); ok {
		r1 = rf(dp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
