// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/edgexfoundry/edgex-go/core/domain/models"

// DeviceClient is an autogenerated mock type for the DeviceClient type
type DeviceClient struct {
	mock.Mock
}

// Device provides a mock function with given fields: id
func (_m *DeviceClient) Device(id string) (models.Device, error) {
	ret := _m.Called(id)

	var r0 models.Device
	if rf, ok := ret.Get(0).(func(string) models.Device); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Device)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeviceForName provides a mock function with given fields: name
func (_m *DeviceClient) DeviceForName(name string) (models.Device, error) {
	ret := _m.Called(name)

	var r0 models.Device
	if rf, ok := ret.Get(0).(func(string) models.Device); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(models.Device)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLastConnected provides a mock function with given fields: id, time
func (_m *DeviceClient) UpdateLastConnected(id string, time int64) error {
	ret := _m.Called(id, time)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(id, time)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLastConnectedByName provides a mock function with given fields: name, time
func (_m *DeviceClient) UpdateLastConnectedByName(name string, time int64) error {
	ret := _m.Called(name, time)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(name, time)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLastReported provides a mock function with given fields: id, time
func (_m *DeviceClient) UpdateLastReported(id string, time int64) error {
	ret := _m.Called(id, time)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(id, time)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLastReportedByName provides a mock function with given fields: name, time
func (_m *DeviceClient) UpdateLastReportedByName(name string, time int64) error {
	ret := _m.Called(name, time)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(name, time)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
