// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// ServiceClient is an autogenerated mock type for the ServiceClient type
type ServiceClient struct {
	mock.Mock
}

// UpdateLastConnected provides a mock function with given fields: id, time
func (_m *ServiceClient) UpdateLastConnected(id string, time int64) error {
	ret := _m.Called(id, time)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(id, time)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLastReported provides a mock function with given fields: id, time
func (_m *ServiceClient) UpdateLastReported(id string, time int64) error {
	ret := _m.Called(id, time)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(id, time)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
